nav:
  - 首頁: index.md
  - ⚠️ 現在怎麼做:
      - 現在怎麼做/index.md
      - 現在怎麼做/為家人與朋友準備
      - 現在怎麼做/為社會與其他人準備
  - 🔥 緊急時怎麼做:
      - 緊急時怎麼做/index.md
      - 緊急時怎麼做/協助急難的家人與朋友
      - 緊急時怎麼做/支援更多急難的人
  - 📂 其他資源: 其他資源
